### ISSUE TITLE
[Business Analytics] [Performance Summary Widget] For the Timestamps where there are no api invocations, api latency is displayed as zero

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1305]
**Description:**
During the highlighted time ranges, there are no api invocations for the two apis. Instead of connecting the timestamps where there are invocations, we have shown zero latency for timestamps which don't have invocations.

<img width="1214" alt="zero" src="https://user-images.githubusercontent.com/3957104/86588684-cee95d80-bfa9-11ea-8bb3-01b76ab9aa64.png">

**Comment by Ketharan** [comment]
Seems this happens because of this https://github.com/wso2/analytics-apim/blob/b552e3891cff4b6a314360846816387bc240d9c2/components/org.wso2.analytics.apim.widgets/PerformanceSummary/src/PerformanceSummaryWidget.jsx#L263

we have the following format for vizG meta data

```
const metadata = {
        names: [api1, api2, api3....., timestamp],
        types: ['linear', 'linear', 'linear'...., time],
};
```
Here when we have selected a number of APIs then we have to add a corresponding numeric value to the data for a given timestamp even though there is no data for particular API. 
ie 
The data unit be like `['api1_hits', 'api2_hits', 'api3_hits'....., timestamp]` here we can't skip any api_hit values.
Seems like a limitation with vizG

**Comment by Ketharan** [comment]
Possibly identical with https://github.com/wso2/analytics-apim/issues/1253

**Comment by TanyaM** [comment]
Zero is shown as  it is a limitation in the VizG and since its technically correct, closing this issue.
