### ISSUE TITLE
While Setting up quick setup  WSO2 APIM-ANALYTIC sever getting black screen

### ISSUE THREAD

**Issue by soniavarshney** [wso2/analytics-apim#1346]
Hi Team

When I configure apim 3.1 with analytic server 3.1 its got configured properly because in log I am getting user admin connected.but when try in browser using https://localhost:9643/analytics-dashboard getting black screen without login page and in log below error I am getting

[2020-07-17 00:04:23,752] ERROR {org.wso2.analytics.apim.idp.client.ApimIdPClient} - AM_SYSTEM_APPS does not exists in the AM_DB database.
[2020-07-17 00:04:31,314] ERROR {org.wso2.analytics.apim.idp.client.ApimIdPClient} - AM_SYSTEM_APPS does not exists in the AM_DB database.

**Comment by fazlan-nazeem** [comment]
Hi @soniavarshney,

By default, you need to unzip APIM and APIM-Analytics distributions to the same parent directory when the product is configured to use H2 DB. This requirement is not needed if you are using an external RDBMS. The above issue happens because you haven't unzipped both products to the same parent directory.

**Comment by soniavarshney** [comment]
Ok thanks but I unzip in same directory but now I setup with physical dB so
it’s working fine.
