### ISSUE TITLE
Widgets generated in 3.1.0 should not work with 3.0.0

### ISSUE THREAD

**Issue by BurakKarayel** [wso2/analytics-apim#1406]
@ruks I created my custom widget by using custom widget generator tool in APIM analytics 3.1.0. After that I deployed my custom widget to the APIM Analytics Dashboard 3.0.0 "<SP_HOME>/wso2/dashboards/deployment/web-ui-apps/portal/extensions/widgets directory" directory. However, I couldn't see my widget in dashboard (Analytics dashboard 3.0.0). When I was creating custom widget, I followed the principles mentioned at this page 

[1] https://apim.docs.wso2.com/en/latest/learn/analytics/creating-custom-widgets-in-analytics-dashboards/

**Comment by ruks** [comment]
Have you deployed generated widget into the dashboard and restarted? Also, did you check and observe any errors in the browser console.  
Maybe what you can do is, take an existing widget source[1] and modify according to your requirement. Because 3.1.0 tool may generate widget with incompatible npm dependency. 

[1] https://github.com/wso2/analytics-apim/tree/v3.0.0/components/org.wso2.analytics.apim.widgets/APIMApiBackendUsageSummary

**Comment by BurakKarayel** [comment]
Also another problem, when I tried to create custom widget by using widget generator tool in 3.1.0 version, widgetConf json file is empty in dist folder and produced js file not similar to built in widget's js files.


![image](https://user-images.githubusercontent.com/64360783/88626900-17c99900-d0b4-11ea-9863-97b1e3548ebc.png)

![image](https://user-images.githubusercontent.com/64360783/88626923-20ba6a80-d0b4-11ea-8548-6feaa2838dbe.png)

![image](https://user-images.githubusercontent.com/64360783/88626942-2ca62c80-d0b4-11ea-8bb8-015556b07003.png)

**Comment by ruks** [comment]
Closing the issue since it is not supported
