### ISSUE TITLE
Dimension Selector widget malfunctions for some sequence of steps

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#1454]
**Description:**
Dimension Selector widget malfunctions when switching between dimensions after selecting more than one apis or api provider.

**Affected Product Version:**
3.2.0

**Steps to reproduce:**

1. Select two apis from selector
2. Switch dimension to API Provider. Only one api selection will be cleared and one api will remain under API Provider dimension

<img width="939" alt="Screen Shot 2020-09-22 at 3 18 28 PM" src="https://user-images.githubusercontent.com/3957104/93867977-67f55e00-fce7-11ea-9b6b-01c7431a5665.png">

API name and API Provider name both are in the selector when API Provider dimension is selected. And API Name cannot be removed by clicking on the X 

<img width="998" alt="Screen Shot 2020-09-22 at 3 18 58 PM" src="https://user-images.githubusercontent.com/3957104/93867994-6d52a880-fce7-11ea-8ec9-71bfd0199b5e.png">

3.  Switch back to API dimension again. And we can select the same API name again. Ideally it should not be possible. Since comparing the same api with itself doesn't make sense.

<img width="955" alt="Screen Shot 2020-09-22 at 3 21 50 PM" src="https://user-images.githubusercontent.com/3957104/93868154-b0148080-fce7-11ea-9d80-9677c103239d.png">

**Comment by ruwiniwj** [comment]
This might be due to making the autocomplete non-clearable[1]. If we remove it this might get fixed. But if we do remove it then we need to add a condition to the onChange method[2] to avoid removing the last available selection.  

[1]. https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/DimensionSelector/src/Autocomplete.jsx#L336
[2]. https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/DimensionSelector/src/DimensionSelectorWidget.jsx#L608

**Comment by RAVEENSR** [comment]
> This might be due to making the autocomplete non-clearable[1]. If we remove it this might get fixed. But if we do remove it then we need to add a condition to the onChange method[2] to avoid removing the last available selection to ensure that the autocomplete field will be non-empty .
> 
> [1]. https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/DimensionSelector/src/Autocomplete.jsx#L336
> [2]. https://github.com/wso2/analytics-apim/blob/master/components/org.wso2.analytics.apim.widgets/DimensionSelector/src/DimensionSelectorWidget.jsx#L608

This suggested fix did not work
