### ISSUE TITLE
apim analytics 3.2.0 deployment yaml issue

### ISSUE THREAD

**Issue by kalevivek11** [wso2/analytics-apim#1477]
Analytics dashboard yaml file
auth.configs:
  type: apim
  ssoEnabled: true
  properties:
    adminScope: apim_analytics:admin_carbon.super
    allScopes: apim_analytics:admin apim_analytics:product_manager apim_analytics:api_developer apim_analytics:app_developer apim_analytics:devops_engineer apim_analytics:analytics_viewer apim_analytics:everyone openid apim:api_view apim:subscribe
    adminServiceBaseUrl: https://publisherdomain9445
    **adminUsername**: admin
    adminPassword: admin

if you use any other username than **admin** it gives error invalid username in publisher logs

**Comment by RAVEENSR** [comment]
@kalevivek11 
That is because you have not correctly renamed the admin password or did not create the new admin user in the correct manner.

If you have started the wso2server.sh once and then replace the admin username and password with your new username and password it will not work properly. Since you have already started the server, the default `admin` user will be created as the super tenant username. What you can do is changing the password of that already created `admin` user. To do that refer [1, 2]. Then you need to change the analytics worker **deployment.yaml** file(need to provide the base64 encoded new password for `auth.configs` password field) and the analytics dashboard **deployment.yaml** file(need to provide new admin password for `adminPassword`, `kmPassword` entries in the `auth.configs` and under  `# credentials for worker nodes` section)

If you change the admin username and admin password for super tenant in the deployment.yaml of the API Manager before starting the server for the first time, it will create the admin user that you have provided. Then as mentioned above, you need to provide the new admin username and new admin passwords for  analytics worker **deployment.yaml** file and the analytics dashboard **deployment.yaml** file.

Let's say you have now already started the server and you want to change the admin username and admin password. Then you need to log into the management console as the super tenant admin user(still the APIM **deployment.toml** file has `admin/admin` as the super tenant credentials) and create new user with the admin role and assign other necessary admin roles for already created service provider(SP) apps. Then you can stop the APIM server and change the super tenant credentials in the **deployment.toml** file of the API Manager. After that, as mentioned above, you need to provide the new admin username and new admin passwords for  analytics worker **deployment.yaml** file and the analytics dashboard **deployment.yaml** file.

I have tested these scenarios and they are working as expected.

[1] https://apim.docs.wso2.com/en/3.0.0/administer/product-security/logins-and-passwords/maintaining-logins-and-passwords/#maintaining-logins-and-passwords
[2] https://docs.wso2.com/display/ADMIN44x/Changing+a+Password

**Comment by kalevivek11** [comment]
@RAVEENSR thank you for valuable comments
