### ISSUE TITLE
API usage statistics fluctuating

### ISSUE THREAD

**Issue by tgtshanika** [wso2/analytics-apim#633]
> **Description:**
> While doing a PoC for a customer I've noticed that the API usage statistics are fluctuating. When I check the usage data in the API_REQUEST_SUMMARY table the total request count for an API changes, having an impact on the statistics shown in the Store and the Publisher.
> 
> This issue happens on different types of set-up. I've noticed this when API Manager 2.0.0 and the Analytics were installed on the same machine using H2 database. It also happened when I switched to a MySql database. 
> I now have an installation where APIM 2.0.0 and the Analytics run on a different server, using MySql as database.
> 
> In the example below you can see that on August 31 the total amount of requests on August 29 changes.
> 
> When I executed the query the first time the total amount of requests for the Monuments 1.0.0 API by user monuments_client is 10 (6 + 4).
> 
> mysql> select * from API_REQUEST_SUMMARY;

By Glenn Boschmans from https://wso2.org/jira/browse/ANLYAPIM-128

**Comment by tgtshanika** [comment]
Please refer https://wso2.org/jira/browse/ANLYAPIM-128 for mysql query results.

**Comment by ruks** [comment]
from APIM 2.6.0 onwards analytics are refactored and now using only realtime analytics. With that analytics use, siddhi aggregated streams to read and summarised data using multiple granularity level tables. Also, direct DB access not happen now and use the abstract DB independence siddhi queries to fetch the data. 
Since this is not relevant now closing.
