### ISSUE TITLE
Overall API Stats widget displays incorrect information until alerts are enabled.

### ISSUE THREAD

**Issue by TanyaM** [wso2/analytics-apim#779]
**Description:**
This particular widget display whether apis are available or not. Until alerts are configured this widget display as all the apis are available (100%).

IMO  coupling alerts with default publisher dashboard is wrong. 
If this widget is really required we have to 

1. Specify in the docs that alerts needs to be configured to see the correct info.
2. Fix the widget so that it won't show anything until alerts are configured.

**Affected Product Version:**
3.0.0

**Comment by ruwiniwj** [comment]
Since the alerts are enabled in the worker profile and widgets are displayed in the dashboard profile  we are unable to verify whether alerts are enabled prior to displaying the widget. Therefore, a helper text was added to to API availability widget to inform the user that the widget requires analytics to be enabled.
Fixed with https://github.com/wso2/analytics-apim/pull/802
